project:
  type: website
  output-dir: docs

website:
  title: "Duval's Blog"
  site-url: https://pgduval.github.io/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

