---
title: "Setup this blog"
author: "Philippe G-Duval"
date: "2023-12-26"
categories: [news]
---

Documenting the setup of this blog.

For posterity but mostly for my future self. Overall I'm quite impress by the simplicity and easy of use of Quarto.

I'm following the quarto documentation here: [Quarto](https://quarto.org/docs/guide/) more specifically the [Creating a Blog](https://quarto.org/docs/websites/website-blog.html) guide.

## Setup

First, I installed the package in RStudio: `install.packages("quarto")` Then, in RStudio, I created a new project using the Quarto template. We need to reopen Rstudio after installing quarto for the option to become visible. Then I selected: `File > New Project > Quarto Blog`.

## Publish

To publish I followed instruction here [Github Pages](https://quarto.org/docs/publishing/github-pages.html).

Somes notes:

-   It's important to create the `gh-pages` branch before publishing.
-   As we installed the package from RStudio the quarto commands needs to be executed from the Terminal windows in RStudio.

Updating the blog is simply a matter of:

1.  Making the change on the `main` branch
2.  Commiting the changes
3.  Publish with `quarto publish gh-pages`

The `quarto publish` commands automatically render and commit the changes on `main` to the `gh-pages` branch. It then push the changes to github.
